Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/03/2022
Var
// Seção de Declarações das variáveis 
peso, altura, imc: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("Peso: ")
leia(peso)
escreva("Altura: ")
leia(altura)
imc <- peso/(altura*altura)
escreva("IMC: ",imc:2:2)


Fimalgoritmo